/* Regenerates games/shabda/words-{4,5,6,7}.js with a full guess lexicon.
   ANSWERS are preserved verbatim and in order — the daily schedule is a seeded
   shuffle of that array, so any reordering would rewrite six months of history. */
const fs = require('fs'), vm = require('vm'), os = require('os'), path = require('path');
const GAME = __dirname + '/';

/* ENABLE is a public-domain word list. It is cached in the temp folder rather
   than kept here: it is a build input, not something the game ships. */
const ENABLE_URL = 'https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt';
const CACHE = path.join(os.tmpdir(), 'shabda-enable1.txt');

async function loadEnable() {
  if (!fs.existsSync(CACHE)) {
    process.stdout.write('fetching ENABLE... ');
    const res = await fetch(ENABLE_URL);
    if (!res.ok) throw new Error('could not fetch ENABLE: HTTP ' + res.status);
    fs.writeFileSync(CACHE, await res.text(), 'utf8');
    console.log('cached at ' + CACHE);
  }
  return new Set(fs.readFileSync(CACHE, 'utf8').split(/\r?\n/)
    .map(s => s.trim().toLowerCase()).filter(w => /^[a-z]{4,7}$/.test(w)));
}

/* Words in daily use that both lexicons miss: ENABLE was frozen in 1997 and the
   larger word lists are no fresher. Extend this by hand as needed. */
const MODERN = `blog blogs vlog vlogs wiki wikis wifi apps emoji meme memes texted webcam
  login logout online email emails inbox spammy unmute reboot router laptop tablet screen
  selfie avatar upload stream tweet tweets geeky techie zoomed reblog unsend
  sudoku ramen latte lattes nachos vegan sushi wasabi taco tacos kimchi quinoa panini
  detox vape vapes decaf combo hoodie sneaker`.split(/\s+/).filter(w => /^[a-z]{4,7}$/.test(w));

/* Load what is there now: answers (curated, order-critical) and the old extras. */
const ctx = { console }; ctx.window = ctx; vm.createContext(ctx);
for (const f of ['words-4.js', 'words-5.js', 'words-6.js', 'words-7.js'])
  vm.runInContext(fs.readFileSync(GAME + f, 'utf8').replace(/^\uFEFF/, ''), ctx, { filename: f });
const CURRENT = ctx.WORD_LISTS;

const usable = (list, len) => list.filter(w => w.length === len && /^[a-z]+$/.test(w));
const chunk = (arr, n) => { const o = []; for (let i = 0; i < arr.length; i += n) o.push(arr.slice(i, i + n)); return o; };

async function main() {
const enable = await loadEnable();
const report = [];
for (const len of [4, 5, 6, 7]) {
  const answers = usable(CURRENT[len].answers, len);          // exactly what BANK uses today
  const extras  = usable(CURRENT[len].extra || [], len);

  /* Whatever the files already accept is an input, so re-running this never
     narrows the lexicon - words added by hand since the last run survive. */
  const packed = CURRENT[len].valid || '';
  const existing = [];
  for (let i = 0; i + len <= packed.length; i += len) existing.push(packed.slice(i, i + len));

  const valid = [...new Set([
    ...[...enable].filter(w => w.length === len),
    ...MODERN.filter(w => w.length === len),
    ...answers,
    ...extras,
    ...existing
  ])].sort();

  const answerBlock = chunk(answers.map(w => `'${w}'`), 10)
    .map(row => '  ' + row.join(',')).join(',\n');
  const validBlock = chunk(valid, 20).map(row => `  '${row.join('')}'`).join(',\n');

  const word = { 4: 'Four', 5: 'Five', 6: 'Six', 7: 'Seven' }[len];
  const file = `/* ${word}-letter word data for Shabda.

   ANSWERS - the pool the daily and random solutions are drawn from: common,
             fairly guessable words only. The order matters. words.js shuffles
             this array with a fixed seed to lay out the daily schedule, so
             reordering or removing entries rewrites which word fell on which
             past date. Append to the end if you want to add answers.

   VALID   - every word accepted as a guess, ${valid.length} of them. Packed as
             fixed-width text, ${len} characters per word and no separators,
             which stores them in about ${Math.round(valid.length * len / 1024)} KB instead of the ~${Math.round(valid.length * (len + 3) / 1024)} KB the
             same words would take as a quoted array. words.js slices it back
             apart at load. Sources: the ENABLE lexicon (public domain), plus a
             hand-kept list of modern words both lexicons predate, plus every
             word this game already accepted.

   Regenerated by _gen-words.js — hand edits are fine, but keep
   ANSWERS in order and keep VALID rows a whole number of words wide. */
(function () {

const ANSWERS = [
${answerBlock}
];

const VALID = [
${validBlock}
].join('');

window.WORD_LISTS = window.WORD_LISTS || {};
window.WORD_LISTS[${len}] = { answers: ANSWERS, valid: VALID };

})();
`;
  fs.writeFileSync(GAME + `words-${len}.js`, file, 'utf8');
  report.push(`${len}-letter: ${answers.length} answers, ${valid.length} valid -> ${(file.length / 1024).toFixed(0)} KB`);
}
console.log(report.join('\n'));
}

main().catch(err => { console.error(err.message); process.exit(1); });
