/* Cuts puzzles.json / puzzles.js — the small dated window the game actually
   plays from and the only copy of the manifest that is ever committed.

   _gen-puzzles.js authors every day out to its DAYS constant and leaves the
   result in the OS temp folder, because a public repository is read by
   anyone, git history included, and a year of future answers sitting in a
   file is a spoiler no matter whether the deployed site links to it. This
   script takes that full manifest and keeps only a window around today: a
   couple of days of slack behind (the game only ever reads today's date, but
   a clock a little behind the server's should still see a day it recognises)
   and a month ahead, so the window does not need cutting again next week.

   Run this again — no need to re-run _gen-puzzles.js — whenever the window's
   far edge is close. It says so on the way out. Each run reads the same
   cached full manifest, so two runs a month apart produce overlapping windows
   from the same schedule, not a reshuffled one. */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { containsProfanity } = require('./profanity.js');

const OUT_DIR = __dirname;
const FULL_MANIFEST_CACHE = path.join(os.tmpdir(), 'anagram-manifest-full.json');

const PAST_DAYS = 2;       // slack only — nothing in the client reads a date but today's
const FUTURE_DAYS = 30;    // the window; re-run before this runs out

const ZONE = 'America/New_York';

/* Matches assets/daily.js's key(): the calendar date as it reads in New York,
   so the window lines up with the date the browser will actually ask for. */
function todayKey() {
  const parts = {};
  new Intl.DateTimeFormat('en-US', {
    timeZone: ZONE, year: 'numeric', month: '2-digit', day: '2-digit'
  }).formatToParts(new Date()).forEach(part => { parts[part.type] = part.value; });
  return `${parts.year}-${parts.month}-${parts.day}`;
}

function shiftKey(key, days) {
  const ms = Date.parse(key + 'T00:00:00Z') + days * 86400000;
  return new Date(ms).toISOString().slice(0, 10);
}

function main() {
  if (!fs.existsSync(FULL_MANIFEST_CACHE)) {
    console.error(`No full manifest at ${FULL_MANIFEST_CACHE}.`);
    console.error('Run node _gen-puzzles.js first — it authors the full schedule and leaves it there.');
    process.exit(1);
  }

  const full = JSON.parse(fs.readFileSync(FULL_MANIFEST_CACHE, 'utf8'));
  const today = todayKey();
  const from = shiftKey(today, -PAST_DAYS);
  const to = shiftKey(today, FUTURE_DAYS);

  const days = full.days.filter(d => d.date >= from && d.date <= to);
  if (!days.some(d => d.date === today)) {
    console.error(`The full manifest has no entry for today (${today}) inside its own range ` +
      `(${full.days[0].date} to ${full.days[full.days.length - 1].date}).`);
    console.error('Re-run node _gen-puzzles.js to author further out, then publish again.');
    process.exit(1);
  }

  /* _gen-puzzles.js already keeps every one of these out of the pool a word
     is drawn from — this should never actually trip. It is here because this
     script is meant to run unattended, on a schedule, with nobody reading the
     window before it ships. Anything caught here is written nowhere: the
     command exits non-zero instead, so an automated run surfaces it rather
     than publishing over it.

     The word only, not its definition — a dictionary definition is free text
     about the word, and words on this list turn up in it entirely innocently
     ("nursing: to feed at the breast"). Flagging prose written about a clean
     word is not the thing being guarded against here. */
  const flagged = [...days, ...full.practice].filter(entry => containsProfanity(entry.w));
  if (flagged.length) {
    console.error(`Refusing to publish: ${flagged.length} entr${flagged.length === 1 ? 'y' : 'ies'} ` +
      'flagged by the profanity check:');
    flagged.forEach(entry => console.error(`  ${entry.date || 'practice'}: "${entry.w}"`));
    process.exit(1);
  }

  const manifest = {
    schemaVersion: full.schemaVersion,
    launchDate: full.launchDate,
    days,
    practice: full.practice
  };

  const json = JSON.stringify(manifest);
  fs.writeFileSync(path.join(OUT_DIR, 'puzzles.json'), JSON.stringify(manifest, null, 1), 'utf8');

  /* The same window as a plain script. Parea's games open straight off the
     filesystem, where fetch() of a local JSON file is blocked, so the
     loadable copy is a one-line global assignment. */
  fs.writeFileSync(path.join(OUT_DIR, 'puzzles.js'),
    '/* Generated by _publish-puzzles.js — do not edit by hand.\n' +
    `   A ${PAST_DAYS + FUTURE_DAYS + 1}-day window of the manifest, wrapped so it loads without a server. */\n` +
    'window.ANAGRAM_MANIFEST = ' + json + ';\n', 'utf8');

  console.log(`published ${days.length} days: ${from} to ${to} (today is ${today})`);
  console.log(`practice pool: ${manifest.practice.length} words`);
  console.log(`\nre-run this before ${to} — after that the client has no puzzle for the day.`);
}

main();
